version: 2

builds:
  - main: ./multirun.go
    binary: multirun
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

homebrew_casks:
  - repository:
      owner: ericfialkowski
      name: homebrew-tap
    homepage: https://github.com/ericfialkowski/multirun
    description: Run multiple commands concurrently
